name: 自动执行-直接执行

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 运行批处理
        run: .\uup-auto-run.cmd
        shell: cmd

      - name: 上传ISO
        uses: actions/upload-artifact@v4
        with:
          name: iso-file
          path: "*.iso"
          if-no-files-found: error
